"""Automatic cleanup of downloaded files.

Rules are configurable (Configurações → Limpeza automática): remove files that
were already downloaded (or blocked) and are older than N days, so the server
reclaims disk without touching files the user has not taken yet.

Safety defaults: only ``downloaded``/``blocked`` records are candidates, never
one with a download in flight, and **originals are left alone** unless the user
opts in — cleanup mainly targets files generated by conversion. The download
history (``file_records``/``download_events``) is preserved: the record is only
moved to ``deleted``.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

from app.database.models import Book, FileState
from app.downloads import store

logger = logging.getLogger(__name__)

#: How many files one pass handles, so a big backlog is spread over ticks.
DEFAULT_LIMIT = 200


@dataclass(slots=True)
class CleanupRule:
    days: int = 30
    include_originals: bool = False
    states: tuple[str, ...] = (FileState.DOWNLOADED.value, FileState.BLOCKED.value)
    limit: int = DEFAULT_LIMIT

    @classmethod
    def from_settings(cls, settings) -> CleanupRule:
        return cls(
            days=max(1, int(getattr(settings, "download_cleanup_days", 30) or 30)),
            include_originals=bool(
                getattr(settings, "download_cleanup_include_originals", False)
            ),
        )


def _eligible(session, rule: CleanupRule):
    return store.cleanup_candidates(
        session,
        states=rule.states,
        idle_seconds=rule.days * 86400,
        limit=rule.limit,
    )


def plan(session, rule: CleanupRule) -> list[dict]:
    """What a run would remove right now (no changes)."""
    rows: list[dict] = []
    for record in _eligible(session, rule):
        book = session.get(Book, record.book_id) if record.book_id else None
        if book is None or (not rule.include_originals and book.is_original):
            continue
        rows.append(
            {
                "book_id": book.id,
                "title": book.title,
                "format": book.format,
                "file_name": record.file_name,
                "size_bytes": record.size_bytes or book.file_size or 0,
                "state": record.state,
                "last_download_at": record.last_download_at,
            }
        )
    return rows


def run(session, rule: CleanupRule) -> dict:
    """Delete the eligible files and mark their records as deleted."""
    from app.library import service

    result = {"removed": 0, "freed_bytes": 0, "skipped": 0, "orphans": 0}
    for record in _eligible(session, rule):
        book = session.get(Book, record.book_id) if record.book_id else None
        if book is None:
            # The book is already gone: just close the record.
            record.book_id = None
            record.state = FileState.DELETED.value
            result["orphans"] += 1
            continue
        if not rule.include_originals and book.is_original:
            result["skipped"] += 1
            continue

        freed = record.size_bytes or book.file_size or 0
        title = book.title
        try:
            service.delete_books(session, [book], delete_files=True)
        except Exception:  # noqa: BLE001 - one file must not stop the cleanup
            logger.exception("cleanup could not delete a file", extra={"book_id": record.book_id})
            result["skipped"] += 1
            continue
        record.book_id = None
        record.state = FileState.DELETED.value
        result["removed"] += 1
        result["freed_bytes"] += freed
        logger.info(
            "cleanup removed a downloaded file",
            extra={"title": title, "bytes": freed},
        )

    if result["removed"] or result["orphans"]:
        session.commit()
    return result


__all__ = ["CleanupRule", "plan", "run"]
